### ISSUE TITLE
[EPIC] extension dynamic loading, tree shaking, understanding modules, ...

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/app-playground#2]
If I understand this correctly we cannot use webpack split mechanisms because at compile time all chunks need to be available and they need to be explicitly named in the code:

https://webpack.js.org/guides/code-splitting/#dynamic-imports

**Comment by felixboehm** [comment]
webpack chunks are not amd modules and can not loaded via requirejs

rollup is a solution here

@LukasHirt prototype -> #3

**Comment by felixboehm** [comment]
Collecting different ideas

> FYI: a web component can easily be loaded via requirejs - see https://github.com/owncloud/phoenix/pull/2584/files#diff-7d271f2c0c292de60eb38753c3f74438R39

> Here is how a web component is built using vue cli3: https://github.com/DeepDiver1975/phoenix-demo-web-component

👍 
Maybe a good alternative to rollup. 
- check treeshaking, are libs loaded twice?
- agree on a preferred / recommended way of building extension
